import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mona = localFont({
  src: [
    {
      path: "../../public/fonts/MonaSans-Light.woff2",
      weight: "300",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mona.variable} font-mona`}>
      <body>{children}</body>
    </html>
  );
}
